M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 27 Aug 2022 04:01:22 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-27T16:01:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X147.574Y-89.789
X147.574Y-91.821
X152.654Y-90.805
T0
M30
